export type CatalogCategory =
  | "Property"
  | "Oil & Gas"
  | "Water"
  | "Energy"
  | "Transportation"
  | "Boundaries"
  | "Environment"
  | "Demographics"
  | "Land";
export type ConnectionType = "live" | "refresh" | "download";

export interface CatalogEntry {
  id: string;
  name: string;
  agency: string;
  category: CatalogCategory;
  description: string;
  url?: string;
  sourcePage?: string;
  geometry: "polygon" | "line" | "point";
  keywords: string[];
  requiresViewport?: boolean;
  minZoom?: number;
  countyField?: string;
  connection: ConnectionType;
  updateCadence: string;
  states: string[] | "US";
  license: string;
}

const tx = (entry: Omit<CatalogEntry, "states">): CatalogEntry => ({ ...entry, states: ["TX"] });
const live = { connection: "live" as const, updateCadence: "Publisher managed" };

/** Curated public-agency services. Download records are clearly marked and never masquerade as APIs. */
export const catalog: CatalogEntry[] = [
  tx({
    id: "tx-parcels",
    name: "Texas Land Parcels by County",
    agency: "Texas Geographic Information Office",
    category: "Property",
    geometry: "polygon",
    ...live,
    description:
      "County appraisal parcel boundaries with owner, situs, legal area, land/improvement/market value and tax-year fields where supplied.",
    url: "https://feature.geographic.texas.gov/arcgis/rest/services/Parcels/stratmap_land_parcels_48_most_recent/MapServer/0",
    sourcePage: "https://geographic.texas.gov/stratmap/land-parcels/",
    keywords: ["parcel", "property", "tax", "owner", "appraisal", "cad"],
    requiresViewport: true,
    minZoom: 12,
    countyField: "county",
    license: "TxGIO / contributing appraisal districts",
  }),
  tx({
    id: "txdot-roadways",
    name: "State Roadways",
    agency: "Texas Department of Transportation",
    category: "Transportation",
    geometry: "line",
    ...live,
    description: "State-maintained roadway centerlines with route and highway-system attributes.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_Roadways/FeatureServer/0",
    sourcePage: "https://www.txdot.gov/data-maps.html",
    keywords: ["road", "highway", "centerline", "route"],
    requiresViewport: true,
    minZoom: 7,
    license: "Texas open data",
  }),
  tx({
    id: "txdot-aadt",
    name: "Traffic Count Locations",
    agency: "Texas Department of Transportation",
    category: "Transportation",
    geometry: "point",
    ...live,
    description: "Annual average daily traffic count locations and volumes.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_AADT_Annuals/FeatureServer/0",
    sourcePage: "https://www.txdot.gov/data-maps.html",
    keywords: ["traffic", "aadt", "count", "volume"],
    requiresViewport: true,
    minZoom: 8,
    license: "Texas open data",
  }),
  tx({
    id: "tx-railroads",
    name: "Railroads",
    agency: "Texas Department of Transportation",
    category: "Transportation",
    geometry: "line",
    ...live,
    description: "Active and mapped railroad corridors across Texas.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/Texas_Railroads/FeatureServer/0",
    sourcePage: "https://www.txdot.gov/data-maps.html",
    keywords: ["rail", "railroad", "freight"],
    requiresViewport: true,
    minZoom: 6,
    license: "Texas open data",
  }),
  tx({
    id: "tx-airports",
    name: "Airport Boundaries",
    agency: "Texas Department of Transportation",
    category: "Transportation",
    geometry: "polygon",
    ...live,
    description: "Mapped public-use airport footprints and attributes.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/Texas_Airport_Boundaries/FeatureServer/0",
    sourcePage: "https://www.txdot.gov/data-maps.html",
    keywords: ["airport", "aviation", "runway"],
    minZoom: 7,
    license: "Texas open data",
  }),
  tx({
    id: "tx-cities",
    name: "City Boundaries",
    agency: "Texas Department of Transportation",
    category: "Boundaries",
    geometry: "polygon",
    ...live,
    description: "Incorporated city boundary polygons.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/TxDOT_City_Boundaries/FeatureServer/0",
    sourcePage: "https://www.txdot.gov/data-maps.html",
    keywords: ["city", "municipal", "limit", "boundary"],
    requiresViewport: true,
    minZoom: 6,
    license: "Texas open data",
  }),
  tx({
    id: "tx-counties",
    name: "County Boundaries",
    agency: "Texas Geographic Information Office",
    category: "Boundaries",
    geometry: "polygon",
    ...live,
    description: "All 254 county polygons with names and FIPS codes.",
    url: "https://services.arcgis.com/KTcxiTD9dsQw4r7Z/arcgis/rest/services/Texas_County_Boundaries/FeatureServer/0",
    sourcePage: "https://geographic.texas.gov/",
    keywords: ["county", "fips", "boundary"],
    license: "Texas open data",
  }),
  tx({
    id: "tx-groundwater-wells",
    name: "Groundwater Wells",
    agency: "Texas Water Development Board",
    category: "Water",
    geometry: "point",
    ...live,
    description:
      "Groundwater well locations and available construction, depth and water-level attributes.",
    url: "https://services2.arcgis.com/LYMgRMwHfrWWEg3s/arcgis/rest/services/TWDB_Groundwater_Wells/FeatureServer/0",
    sourcePage: "https://www.twdb.texas.gov/mapping/resources.asp",
    keywords: ["well", "groundwater", "depth", "drilling"],
    requiresViewport: true,
    minZoom: 8,
    license: "Texas public data",
  }),
  tx({
    id: "tx-public-water-wells",
    name: "Public Water System Wells",
    agency: "Texas Commission on Environmental Quality",
    category: "Water",
    geometry: "point",
    ...live,
    description: "Public water system well locations reported to the state.",
    url: "https://services2.arcgis.com/LYMgRMwHfrWWEg3s/arcgis/rest/services/TCEQ_Public_Water_System_Wells/FeatureServer/0",
    sourcePage: "https://gis-tceq.opendata.arcgis.com/",
    keywords: ["public water", "well", "drinking"],
    requiresViewport: true,
    minZoom: 8,
    license: "Texas public data",
  }),
  tx({
    id: "tx-major-aquifers",
    name: "Major Aquifers",
    agency: "Texas Water Development Board",
    category: "Water",
    geometry: "polygon",
    ...live,
    description: "Mapped extents of Texas major aquifers.",
    url: "https://services2.arcgis.com/LYMgRMwHfrWWEg3s/arcgis/rest/services/TWDB_Major_Aquifers/FeatureServer/0",
    sourcePage: "https://www.twdb.texas.gov/mapping/resources.asp",
    keywords: ["aquifer", "groundwater", "major"],
    license: "Texas public data",
  }),
  tx({
    id: "tx-minor-aquifers",
    name: "Minor Aquifers",
    agency: "Texas Water Development Board",
    category: "Water",
    geometry: "polygon",
    ...live,
    description: "Mapped extents of Texas minor aquifers.",
    url: "https://services2.arcgis.com/LYMgRMwHfrWWEg3s/arcgis/rest/services/TWDB_Minor_Aquifers/FeatureServer/0",
    sourcePage: "https://www.twdb.texas.gov/mapping/resources.asp",
    keywords: ["aquifer", "groundwater", "minor"],
    license: "Texas public data",
  }),
  tx({
    id: "tx-transmission",
    name: "Electric Transmission Lines",
    agency: "U.S. Energy Information Administration",
    category: "Energy",
    geometry: "line",
    ...live,
    description:
      "Transmission corridors with voltage and connected-substation attributes where available.",
    url: "https://services2.arcgis.com/FiaPA4ga0iQKduv3/ArcGIS/rest/services/US_Electric_Power_Transmission_Lines/FeatureServer/0",
    sourcePage: "https://www.eia.gov/maps/",
    keywords: ["electric", "transmission", "power", "voltage", "substation"],
    requiresViewport: true,
    minZoom: 6,
    license: "U.S. public data",
  }),
  tx({
    id: "tx-pipelines",
    name: "Natural Gas Pipelines",
    agency: "U.S. Energy Information Administration",
    category: "Energy",
    geometry: "line",
    ...live,
    description: "Interstate and intrastate natural-gas transmission pipelines.",
    url: "https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Natural_Gas_Interstate_and_Intrastate_Pipelines_1/FeatureServer/0",
    sourcePage: "https://www.eia.gov/maps/",
    keywords: ["pipeline", "gas", "energy", "midstream"],
    requiresViewport: true,
    minZoom: 6,
    license: "U.S. public data",
  }),
  {
    id: "us-wind-turbines",
    name: "Wind Turbine Locations",
    agency: "U.S. Geological Survey / Lawrence Berkeley National Laboratory",
    category: "Energy",
    geometry: "point",
    ...live,
    states: "US",
    description: "Utility-scale wind turbine locations with project and turbine attributes.",
    url: "https://energy.usgs.gov/arcgis/rest/services/Hosted/uswtdbDyn/FeatureServer/0",
    sourcePage: "https://energy.usgs.gov/uswtdb/",
    keywords: ["wind", "turbine", "renewable"],
    requiresViewport: true,
    minZoom: 7,
    license: "U.S. public data",
  },
  {
    id: "us-solar",
    name: "Large-Scale Solar Facilities",
    agency: "U.S. Geological Survey / Lawrence Berkeley National Laboratory",
    category: "Energy",
    geometry: "polygon",
    ...live,
    states: "US",
    description: "Large-scale photovoltaic facility locations and footprints.",
    url: "https://energy.usgs.gov/arcgis/rest/services/Hosted/uspvdbDyn/FeatureServer/0",
    sourcePage: "https://energy.usgs.gov/uspvdb/",
    keywords: ["solar", "photovoltaic", "renewable"],
    requiresViewport: true,
    minZoom: 7,
    license: "U.S. public data",
  },
  tx({
    id: "glo-psf",
    name: "Permanent School Fund Lands",
    agency: "Texas General Land Office",
    category: "Land",
    geometry: "polygon",
    ...live,
    description: "State-owned Permanent School Fund surface and mineral tracts.",
    url: "https://gisweb.glo.texas.gov/arcgis/rest/services/GLOMapServices/PSFLands/MapServer/0",
    sourcePage: "https://www.glo.texas.gov/land/gis-maps-and-data",
    keywords: ["state land", "psf", "tract", "mineral"],
    requiresViewport: true,
    minZoom: 7,
    license: "Texas public data",
  }),
  tx({
    id: "glo-leases",
    name: "State Oil & Gas Leases",
    agency: "Texas General Land Office",
    category: "Oil & Gas",
    geometry: "polygon",
    ...live,
    description: "State mineral lease tracts administered by the land office.",
    url: "https://gisweb.glo.texas.gov/arcgis/rest/services/GLOMapServices/StateLeases/MapServer/0",
    sourcePage: "https://www.glo.texas.gov/land/gis-maps-and-data",
    keywords: ["lease", "mineral", "oil", "gas"],
    requiresViewport: true,
    minZoom: 8,
    license: "Texas public data",
  }),
  tx({
    id: "rrc-wells",
    name: "Oil & Gas Wells — County Downloads",
    agency: "Railroad Commission of Texas",
    category: "Oil & Gas",
    geometry: "point",
    connection: "download",
    updateCadence: "Publisher files; viewer updated nightly",
    description:
      "Official county well-location shapefiles. Open the source, choose a county file, then drag it onto the map.",
    sourcePage:
      "https://www.rrc.texas.gov/resource-center/research/data-sets-available-for-download/",
    keywords: ["well", "oil", "gas", "api number", "county"],
    license: "Texas public records",
  }),
  tx({
    id: "rrc-permits",
    name: "Drilling Permits — Official Downloads",
    agency: "Railroad Commission of Texas",
    category: "Oil & Gas",
    geometry: "point",
    connection: "download",
    updateCadence: "Daily and master files",
    description: "Official drilling-permit master and daily files with location fields.",
    sourcePage:
      "https://www.rrc.texas.gov/resource-center/research/data-sets-available-for-download/",
    keywords: ["permit", "drilling", "oil", "gas", "operator"],
    license: "Texas public records",
  }),
  {
    id: "epa-echo-facilities",
    name: "EPA-Regulated Facilities",
    agency: "U.S. Environmental Protection Agency",
    category: "Environment",
    geometry: "point",
    connection: "refresh",
    updateCadence: "Weekly on Monday",
    states: "US",
    description:
      "Regulated facility locations with air, water, hazardous-waste, inspection, enforcement and compliance attributes.",
    url: "https://echogeo.epa.gov/arcgis/rest/services/ECHO/Facilities/MapServer/0",
    sourcePage: "https://echo.epa.gov/tools/map-service",
    keywords: ["epa", "echo", "facility", "permit", "compliance", "enforcement", "environment"],
    requiresViewport: true,
    minZoom: 8,
    license: "U.S. public data",
  },
  tx({
    id: "puct-electric-service-areas",
    name: "Electric Service Areas — Official Source",
    agency: "Public Utility Commission of Texas",
    category: "Energy",
    geometry: "polygon",
    connection: "download",
    updateCadence: "Agency-managed filings and viewer",
    description:
      "Approximate electric utility service-area boundaries. Open the official source to obtain the current viewer or filed GIS records.",
    sourcePage: "https://ftp.puc.texas.gov/public/puct-info/industry/maps/",
    keywords: ["electric", "utility", "service territory", "cooperative", "municipal"],
    license: "Texas public records; approximate boundaries",
  }),
  tx({
    id: "tpwd-gis-library",
    name: "Wildlife, Parks & Habitat — Official Downloads",
    agency: "Texas Parks and Wildlife Department",
    category: "Environment",
    geometry: "polygon",
    connection: "download",
    updateCadence: "Publisher managed",
    description:
      "Official wildlife, habitat, ecological and park GIS downloads for drag-and-drop import.",
    sourcePage: "https://tpwd.texas.gov/gis/",
    keywords: ["wildlife", "habitat", "park", "ecology", "species", "conservation"],
    license: "Texas public data; dataset-specific terms",
  }),
  {
    id: "census-tracts",
    name: "2020 Census Tracts",
    agency: "U.S. Census Bureau",
    category: "Demographics",
    geometry: "polygon",
    ...live,
    states: "US",
    description: "Census tract boundaries for demographic joins and analysis.",
    url: "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Tracts_Blocks/MapServer/1",
    sourcePage: "https://www.census.gov/geographies/mapping-files.html",
    keywords: ["census", "tract", "demographic", "population"],
    requiresViewport: true,
    minZoom: 7,
    license: "U.S. public domain",
  },
  {
    id: "nhd-flowlines",
    name: "National Hydrography Flowlines",
    agency: "U.S. Geological Survey",
    category: "Water",
    geometry: "line",
    ...live,
    states: "US",
    description: "Streams, rivers and channels from the national hydrography dataset.",
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/6",
    sourcePage: "https://www.usgs.gov/the-national-map-data-delivery/gis-data-download",
    keywords: ["stream", "river", "creek", "hydrology"],
    requiresViewport: true,
    minZoom: 8,
    license: "U.S. public domain",
  },
];

export const categories = Array.from(new Set(catalog.map((entry) => entry.category)));
export function searchCatalog(
  query: string,
  category: string | null,
  states: string[] = ["TX"],
): CatalogEntry[] {
  const q = query.trim().toLowerCase();
  return catalog.filter((entry) => {
    if (category && entry.category !== category) return false;
    if (entry.states !== "US" && !entry.states.some((state) => states.includes(state)))
      return false;
    return (
      !q ||
      [entry.name, entry.agency, entry.description, ...entry.keywords].some((value) =>
        value.toLowerCase().includes(q),
      )
    );
  });
}
export const US_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];
