import { useState } from 'react'
import { Box, ChevronRight, CircleDot, Combine, Crosshair, Layers, Search, Sparkles, X } from 'lucide-react'
import { ANALYSIS_TOOLS, runAnalysis, type AnalysisOperation } from '../lib/analysis'
import { useGisStore } from '../store'
import type { GisLayer } from '../types'

const ICONS: Record<AnalysisOperation, React.ReactNode> = { buffer: <CircleDot/>, centroids: <Crosshair/>, envelopes: <Box/>, convexHull: <Sparkles/>, dissolve: <Combine/>, selectWithin: <Layers/> }

export default function AnalysisPanel({ onClose, onDone }: { onClose: () => void; onDone: (message: string) => void }) {
  const { layers, activeLayerId, addLayer } = useGisStore(); const [search, setSearch] = useState(''); const [operation, setOperation] = useState<AnalysisOperation>('buffer'); const [sourceId, setSourceId] = useState(activeLayerId ?? layers[0]?.id ?? ''); const [overlayId, setOverlayId] = useState(layers.find((l) => l.id !== sourceId)?.id ?? ''); const [distance, setDistance] = useState(1); const [units, setUnits] = useState<'miles'|'kilometers'|'feet'|'meters'>('miles'); const [error, setError] = useState('')
  const tools = ANALYSIS_TOOLS.filter((tool) => `${tool.name} ${tool.description}`.toLowerCase().includes(search.toLowerCase())); const selected = ANALYSIS_TOOLS.find((t) => t.id === operation)!; const source = layers.find((l) => l.id === sourceId)
  const run = () => { setError(''); try { if (!source) throw new Error('Choose a source layer.'); const overlay = layers.find((l) => l.id === overlayId); const data = runAnalysis(operation, source.data, { distance, units, overlay: overlay?.data }); const name = `${source.name} — ${selected.name}`; addLayer(name, data, { group: 'Analysis results', style: { ...source.style, color: '#7c3aed', opacity: .68 } }); onDone(`${selected.name} created ${data.features.length.toLocaleString()} result features.`) } catch (e) { setError(e instanceof Error ? e.message : 'Analysis failed.') } }
  return <aside className="drawer analysis-drawer"><header><div><span className="eyebrow">Spatial laboratory</span><h2>Analysis tools</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header><div className="search-box"><Search/><input placeholder="Find an analysis tool" value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="analysis-layout"><div className="tool-list">{tools.map((tool) => <button className={operation === tool.id ? 'active' : ''} onClick={() => setOperation(tool.id)} key={tool.id}><span>{ICONS[tool.id]}</span><div><strong>{tool.name}</strong><small>{tool.description}</small></div><ChevronRight/></button>)}</div><div className="tool-options"><h3>{selected.name}</h3><p>{selected.description}</p><label>Source layer<select value={sourceId} onChange={(e) => setSourceId(e.target.value)}>{layers.map((l: GisLayer) => <option value={l.id} key={l.id}>{l.name} ({l.data.features.length})</option>)}</select></label>{selected.needsSecondLayer && <label>Overlay layer<select value={overlayId} onChange={(e) => setOverlayId(e.target.value)}>{layers.filter((l) => l.id !== sourceId).map((l) => <option value={l.id} key={l.id}>{l.name}</option>)}</select></label>}{selected.needsDistance && <div className="distance-row"><label>Distance<input type="number" min="0" step="0.1" value={distance} onChange={(e) => setDistance(+e.target.value)}/></label><label>Units<select value={units} onChange={(e) => setUnits(e.target.value as typeof units)}><option>miles</option><option>kilometers</option><option>feet</option><option>meters</option></select></label></div>}{error && <div className="form-message error">{error}</div>}<button className="primary-btn wide" disabled={!layers.length} onClick={run}><Sparkles/> Run analysis</button><small className="safe-note">Your source stays unchanged. Every result becomes a new layer.</small></div></div></aside>
}
