import { useEffect, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { Check, Cloud, Copy, ExternalLink, Eye, Globe2, Link2, Lock, LogIn, LogOut, Map, Plus, RefreshCw, Share2, UserRound, X } from 'lucide-react'
import { cloudConfigured, listCloudMaps, supabase, updateSharing } from '../lib/supabase'
import type { CloudMap, MapVisibility } from '../types'

export function AccountPanel({ user, onClose, onSignedIn, onOpenLibrary }: { user: User | null; onClose: () => void; onSignedIn: (user: User | null) => void; onOpenLibrary: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mode, setMode] = useState<'login'|'signup'>('login'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (!supabase) return; setBusy(true); setMessage('')
    const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { display_name: email.split('@')[0] } } })
    setBusy(false); if (result.error) setMessage(result.error.message); else { setMessage(mode === 'signup' && !result.data.session ? 'Check your email to confirm your account.' : 'Signed in.'); onSignedIn(result.data.user) }
  }
  const signOut = async () => { await supabase?.auth.signOut(); onSignedIn(null); onClose() }
  return <aside className="drawer account-drawer"><header><div><span className="eyebrow">TerraSketch cloud</span><h2>{user ? 'Your account' : 'Sign in'}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header>
    {!cloudConfigured ? <div className="cloud-empty"><Cloud/><h3>Cloud setup needed</h3><p>The complete login and live-map system is installed. Add the two public Supabase values from <code>.env.example</code>, then run the included SQL migration.</p><pre>VITE_SUPABASE_URL{`\n`}VITE_SUPABASE_ANON_KEY</pre><small>Local maps continue to work without cloud configuration.</small></div> : user ? <div className="account-body"><div className="account-card"><div className="avatar large">{(user.email?.[0] ?? 'U').toUpperCase()}</div><div><strong>{user.user_metadata.display_name ?? user.email?.split('@')[0]}</strong><span>{user.email}</span></div><Check/></div><button className="wide-btn solid" onClick={onOpenLibrary}><Map/> Open map library</button><button className="wide-btn" onClick={signOut}><LogOut/> Sign out</button></div> : <form className="auth-form" onSubmit={submit}><p>Save maps in the cloud and share a live URL with clients or collaborators.</p><label>Email<input className="text-input" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input className="text-input" type="password" minLength={6} required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters"/></label>{message && <div className="form-message">{message}</div>}<button className="primary-btn wide" disabled={busy}>{busy ? <span className="spinner"/> : <LogIn/>}{mode === 'login' ? 'Sign in' : 'Create account'}</button><button type="button" className="sample-link" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></form>}
  </aside>
}

export function SharePanel({ map, user, onClose, onNeedSave }: { map?: CloudMap; user: User | null; onClose: () => void; onNeedSave: () => Promise<CloudMap | undefined> }) {
  const [current, setCurrent] = useState(map); const [visibility, setVisibility] = useState<MapVisibility>(map?.visibility ?? 'link'); const [allowEdit, setAllowEdit] = useState(map?.allow_link_edit ?? false); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState(false); const [message, setMessage] = useState('')
  const ensureMap = async () => { if (current) return current; const saved = await onNeedSave(); if (saved) setCurrent(saved); return saved }
  const apply = async () => { setBusy(true); setMessage(''); try { const target = await ensureMap(); if (!target) return; const updated = await updateSharing(target.id, visibility, allowEdit); setCurrent(updated); setMessage('Sharing updated.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not update sharing.') } finally { setBusy(false) } }
  const link = current ? `${window.location.origin}/map/${current.id}` : ''
  const copy = async () => { let target = current; if (!target) { target = await ensureMap(); if (target) { target = await updateSharing(target.id, visibility, allowEdit); setCurrent(target) } } if (!target) return; const url = `${window.location.origin}/map/${target.id}`; await navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 1800) }
  return <aside className="drawer share-drawer"><header><div><span className="eyebrow">Live map</span><h2>Share & collaborate</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header>
    {!cloudConfigured ? <div className="cloud-empty"><Cloud/><h3>Connect cloud sync first</h3><p>Configure Supabase to turn this map into a live shared project. The database migration and access policies are included in the repository.</p></div> : !user ? <div className="cloud-empty"><UserRound/><h3>Sign in to share</h3><p>An account owns the map and controls whether others can view it.</p></div> : <div className="share-body"><div className="share-intro"><Share2/><div><strong>One map, one live link</strong><p>Every cloud save updates the same link. Open viewers receive changes through realtime sync.</p></div></div><label className={`permission-card ${visibility === 'private' ? 'selected' : ''}`}><input type="radio" checked={visibility === 'private'} onChange={() => setVisibility('private')}/><Lock/><div><strong>Private</strong><span>Only you can open this map.</span></div></label><label className={`permission-card ${visibility === 'link' ? 'selected' : ''}`}><input type="radio" checked={visibility === 'link'} onChange={() => setVisibility('link')}/><Link2/><div><strong>Anyone with the link</strong><span>Unlisted and easy to share.</span></div></label><label className={`permission-card ${visibility === 'public' ? 'selected' : ''}`}><input type="radio" checked={visibility === 'public'} onChange={() => setVisibility('public')}/><Globe2/><div><strong>Public</strong><span>Visible to anyone who knows the map ID.</span></div></label><label className="edit-toggle"><div><strong>Allow signed-in editing</strong><span>People with the link can save changes after signing in.</span></div><input type="checkbox" checked={allowEdit} onChange={(e) => setAllowEdit(e.target.checked)}/></label>{current && <div className="share-link"><input readOnly value={link}/><button onClick={copy}>{copied ? <Check/> : <Copy/>}</button></div>}{message && <div className="form-message">{message}</div>}<button className="primary-btn wide" disabled={busy} onClick={apply}>{busy ? <span className="spinner"/> : <RefreshCw/>} Save sharing</button>{current && <button className="soft-btn wide" onClick={() => window.open(link, '_blank')}><ExternalLink/> Open shared view</button>}</div>}
  </aside>
}

export function MapLibrary({ onClose, onOpen, onNew }: { onClose: () => void; onOpen: (map: CloudMap) => void; onNew: () => void }) {
  const [maps, setMaps] = useState<CloudMap[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState('')
  useEffect(() => { listCloudMaps().then(setMaps).catch((e) => setError(e.message)).finally(() => setBusy(false)) }, [])
  return <aside className="drawer library-drawer"><header><div><span className="eyebrow">Workspace</span><h2>My maps</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header><div className="library-tools"><button className="primary-btn wide" onClick={onNew}><Plus/> New map</button></div>{busy ? <div className="cloud-empty"><span className="spinner"/><p>Loading your maps…</p></div> : error ? <div className="cloud-empty"><p>{error}</p></div> : !maps.length ? <div className="cloud-empty"><Map/><h3>No cloud maps yet</h3><p>Save the current map to create your first live project.</p></div> : <div className="map-list">{maps.map((map) => <button key={map.id} onClick={() => onOpen(map)}><div className="map-preview"><Map/></div><div><strong>{map.title}</strong><span>{map.snapshot.layers.length} layers · {new Date(map.updated_at).toLocaleDateString()}</span></div>{map.visibility === 'private' ? <Lock/> : <Eye/>}</button>)}</div>}
  </aside>
}
